<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$itemMedia = $item->media();
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js', 'text/javascript', ['defer' => 'defer']);

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
?>

<?php $this->trigger('view.show.before'); ?>

<?php if ($itemMedia): ?>
  <div class="container pt-2 pb-3 pt-md-5 pb-md-4">
    <div class="row" id="media-wrapper">
      <div class="col">
        <div class="media-embeds">
          <?php // echo $this->miradorViewer($item); ?>
          <?php
          foreach ($itemMedia as $media) {
            if ($media->mediaType() == "application/pdf") {
              echo $media->render();
              break;
            }
          }
          ?>
        </div>
      </div>
    </div>
  </div>
<?php endif; ?>

<div class="container pt-2 pb-3 py-md-4" id="quick-details">
  <div class="row">
    <div class="col">
      <?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>
      <?php echo $this->CreatorHelper($item); ?>
      <?php
      $departments = [];
      foreach ($item->itemSets() as $itemSet) {
        foreach ($itemSet->value('dcterms:type', ['all' => true]) as $itemSetType) {
          if (($itemSetType == "Department") || ($itemSetType == "Program")) {
            $departments[] = $itemSet->displayTitle();
          }
        }
      }
      ?>
      <?php if ($departments): ?>
        <div class="departments fw-bold text-muted">
          <?php echo implode("; ", $departments) ?>
        </div>
      <?php endif; ?>
      <?php echo $this->SocialShare($item); ?>
    </div>
    <div class="col-sm-auto">
      <?php
      $dataLink = "";
      if (!str_starts_with($itemSet->displayTitle(), "Fashion International")) {
        foreach ($item->value('dcterms:identifier', ['all' => true, 'type' => 'uri']) as $identifier) {
          if ($identifier->value() == "SPARC reference code") {
            $refCode = $identifier->uri();
            $dataLink = "/page/data?issue%5B%5D=" . urlencode($refCode);
            break;
          }
        }
      }
      ?>
      <?php if ($dataLink): ?>
        <a id="map-button" class="btn btn-fit-green floating-action mt-2 mt-sm-0" aria-label="View this issue as data"
          href="<?php echo $dataLink; ?>">
          <span class="action-container">
            <i class="fas fa-table" aria-hidden="true" title="View this issue as data">
            </i>
            Data
          </span>
        </a>
      <?php endif; ?>
    </div>
  </div>
</div>
<div class="container pt-2 pb-3 pt-md-4 pt-md-5">
  <div class="row  justify-content-between">
    <h3 class="mb-4">
      <?php echo $translate('About this Item'); ?>
    </h3>
    <div class="col-lg-6 col-xxl-7">
      <?php echo $item->displayValues(); ?>
    </div>
    <div class="col-lg-5 col-xxl-4">
      <div class="property">
        <h4>
          <?php echo $translate('Citation'); ?>
        </h4>
        <?php echo $this->CitationHelper($item); ?>
      </div>
    </div>
  </div>
</div>




<?php $this->trigger('view.show.after'); ?>