<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$itemMedia = $item->media();
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js', 'text/javascript', ['defer' => 'defer']);
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js', 'text/javascript');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
?>

<?php $this->trigger('view.show.before'); ?>

<?php if ($itemMedia): ?>
  <div class="container pt-2 pb-3 pt-md-5 pb-md-4">
    <div class="row" id="media-wrapper">
      <div class="col">
        <div class="media-embeds">
          <?php
          echo $this->miradorViewer($item, null, [
            'window' => [
              'sideBarPanel' => 'search',
              'sideBarOpen' => false,
              'panels' => [
                'info' => false,
                'attribution' => false
              ]
            ],
            'themes' => [
              'dark' => [
                'palette' => [
                  'type' => 'dark',
                  'primary' => [
                    'main' => '#fec2be',
                  ],
                  'secondary' => [
                    'main' => '#fec2be',
                  ]
                ]
              ],
              'light' => [
                'palette' => [
                  'type' => 'light',
                  'primary' => [
                    'main' => '#fec2be',
                  ],
                  'secondary' => [
                    'main' => '#fec2be',
                  ]
                ]
              ]
            ]
          ]);
          ?>
          <?php
          // foreach ($itemMedia as $media) {
          //   if ($media->mediaType() == "application/pdf") {
          //     echo $media->render();
          //     break;
          //   }
          // }
          ?>
        </div>
      </div>
    </div>
  </div>
<?php endif; ?>

<div class="container pt-2 pb-3 py-md-4" id="quick-details">
  <div class="row">
    <div class="col">
      <?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>
      <?php echo $this->CreatorHelper($item); ?>
      <?php
      $departments = [];
      foreach ($item->itemSets() as $itemSet) {
        foreach ($itemSet->value('dcterms:type', ['all' => true]) as $itemSetType) {
          if (($itemSetType == "Department") || ($itemSetType == "Program")) {
            $departments[] = $itemSet->displayTitle();
          }
        }
      }
      ?>
      <?php if ($departments): ?>
        <div class="departments fw-bold text-muted">
          <?php echo implode("; ", $departments) ?>
        </div>
      <?php endif; ?>
      <?php echo $this->SocialShare($item); ?>
    </div>
    <div class="col-md-auto mt-2 mt-md-0">
      <div class="row">
        <?php
        $refCode = "";
        $iaCode = "";
        foreach ($item->value('dcterms:identifier', ['all' => true, 'type' => 'uri']) as $identifier) {
          if ($identifier->value() == "SPARC reference code") {
            $refCode = $identifier->uri();
          } elseif ($identifier->value() == "Internet Archive ID") {
            $iaCode = $identifier->uri();
          }
        }
        ?>
        <?php if ($refCode && $iaCode): ?>
          <div class="col-auto">
            <div class="dropdown">
              <button class="btn btn-dark floating-action" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="action-container">
                  <i class="fas fa-download" aria-hidden="true" title="Download this issue">
                  </i>
                  Files
                </span>
              </button>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li><button class="dropdown-item" id="pdf-download" data-id="<?php echo $item->id(); ?>">PDF</button>
                </li>
                <li><a class="dropdown-item"
                    href="<?php echo 'https://archive.org/download/' . $iaCode . '/' . $refCode . '_images.tar'; ?>">Tiff
                    (High Res)</a></li>
                <li><a id="text-download" class="dropdown-item" data-id="<?php echo $refCode; ?>"
                    href="<?php echo 'https://archive.org/download/' . $iaCode . '/' . $refCode . '_djvu.txt'; ?>">Text
                    (OCR)</a></li>
              </ul>
            </div>
          </div>
        <?php endif; ?>
        <?php
        $dataLink = "";
        if (!str_starts_with($itemSet->displayTitle(), "Fashion International") && $refCode) {
          $dataLink = "/page/data?issue=" . urlencode($refCode);
        }
        ?>
        <?php if ($dataLink): ?>
          <div class="col-auto">
            <a id="data-button" class="btn btn-dark floating-action" aria-label="View this issue as data"
              href="<?php echo $dataLink; ?>">
              <span class="action-container">
                <i class="fas fa-table" aria-hidden="true" title="View this issue as data">
                </i>
                Data
              </span>
            </a>
          </div>
        <?php endif; ?>
      </div>
    </div>
  </div>
</div>
<div class="container pt-2 pb-3 pt-md-4 pt-md-5">
  <div class="row  justify-content-between">
    <h3 class="mb-4">
      <?php echo $translate('About this Item'); ?>
    </h3>
    <div class="col-lg-6 col-xxl-7">
      <?php echo $item->displayValues(); ?>
    </div>
    <div class="col-lg-5 col-xxl-4">
      <div class="property">
        <h4>
          <?php echo $translate('Citation'); ?>
        </h4>
        <?php echo $this->CitationHelper($item); ?>
      </div>
    </div>
  </div>
</div>




<?php $this->trigger('view.show.after'); ?>