<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->appendAttribute('lang', $this->lang())->appendAttribute('class', 'h-100');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($site->title())->setSeparator(' · ');
$this->headLink(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => $this->assetUrl('img/favicon.ico')], 'PREPEND')
  ->prependStylesheet($this->assetUrl('css/style.css'))
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css', 'screen', null, ['integrity' => 'sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=', 'crossorigin' => 'anonymous'])
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css', 'screen', null, ['integrity' => 'sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN', 'crossorigin' => 'anonymous']);
$this->headScript()
  ->prependFile($this->assetUrl('js/advanced-search.js', 'Omeka'))
  ->prependFile($this->assetUrl('js/theme.js'))
  ->prependFile($this->assetUrl('js/global.js', 'Omeka'))
  ->prependFile('https://unpkg.com/infinite-scroll@4.0.1/dist/infinite-scroll.pkgd.min.js', 'text/javascript')
  ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js', 'text/javascript', ['integrity' => 'sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL', 'crossorigin' => 'anonymous'])
  ->prependFile('https://code.jquery.com/jquery-3.6.0.min.js', 'text/javascript', ['integrity' => 'sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=', 'crossorigin' => 'anonymous']);
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-G2C4GN53HX"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'G-G2C4GN53HX');
  </script>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
</head>

<?php echo $this->htmlElement('body')->appendAttribute('class', 'd-flex flex-column h-100'); ?>
<a class="visually-hidden-focusable" href="#content">
  <?php echo $this->translate('Skip to main content'); ?>
</a>
<?php echo $userBar; ?>
<header class="flex-shrink-0">
  <div class="container pt-5 pb-2 d-none d-md-block">
    <div class="row justify-content-center">
      <div class="col-auto">
        <a href="/" class="logo text-dark text-decoration-none">
          <h1 class="visually-hidden">
            <?php echo $escape($site->title()); ?>
          </h1>
          <img src="<?php echo $this->assetUrl('img/fashion-calendar-type.png'); ?>" title="Logo"
            alt="FIT Fashion Calendar Logo">
        </a>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand  d-md-none" href="<?php echo $site->url(); ?>">
        <img src="<?php echo $this->assetUrl('img/fashion-calendar-type-stacked.png'); ?>" alt="FIT Fashion Calendar">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <?php echo $site->publicNav()->menu()->renderPartialWithParams(['site' => $site,], null, 'common/bootstrap-navigation.phtml'); ?>
      </div>
    </div>
  </nav>
</header>
<div class="flex-shrink-0" id="content" role="main">
  <?php echo $this->content; ?>
</div>
<footer class="footer mt-auto py-3 py-md-5 border-top border-dark bg-light">
  <div class="container small">
    <div class="row justify-content-between">
      <div class="col-md-5 text-center">
        <img class="mb-3" src="<?php echo $this->assetUrl('img/clir-black-with-wordmark.png'); ?>"
          alt="The Council on Library and Information Resources" id="clir-logo">
        <p class="text-left">"The Ruth Finley Collection: Digitizing 70 Years of the <em>Fashion Calendar</em>," and the
          Fashion Calendar Research Database (FCRD) is supported by a <em>Digitizing Hidden Collections</em> grant from
          the <a href="https://www.clir.org/">Council on Library and Information Resources</a> (CLIR). The grant program
          is made possible by funding from the Mellon Foundation.</p>
      </div>
      <div class="col-md-5 text-center">
        <img class="my-3" src="<?php echo $this->assetUrl('img/wordmark-black-1-line.png'); ?>" alt="FIT SUNY Logo"
          id="fit-suny-logo">
        <p>
          ©2023 Fashion Institute of Technology
          <br>
          All rights reserved.
        </p>
        <p class="text-left">The views, opinions, and conclusions expressed in this page are those of the author or
          organization and not necessarily those of the Fashion Institute of Technology or its officers and trustees.
          The author or organization
          is solely responsible for its content.</p>
        <p class="text-left">This site is a joint initiative of the <a
            href="https://www.fitnyc.edu/academics/library/">Gladys
            Marcus Library</a> and the <a
            href="https://www.fitnyc.edu/academics/academic-divisions/liberal-arts/history-of-art/">FIT History of Art
            Department</a>.</p>
      </div>
    </div>
  </div>
</footer>
</body>

</html>